name: Deploy to AWS (dev)

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        name: Deploy to AWS
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v7
              with:
                  node-version: 26

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint

            - name: Build code
              run: npm run build

            # - name: Run tests
            #   run: npm run test

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.2.3
              with:
                  role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
                  aws-region: eu-west-2

            - name: Deploy
              run: npm run deploy
              env:
                  # Backend env
                  CERTIFICATE_ARN: unused
                  DEPLOY_ENV: dev
                  USER_POOL_ID: ${{ vars.USER_POOL_ID }}
                  USER_POOL_CLIENT_ID: ${{ vars.USER_POOL_CLIENT_ID }}

                  # Frontend env
                  VITE_USER_POOL_ID: ${{ vars.USER_POOL_ID }}
                  VITE_USER_POOL_CLIENT_ID: ${{ vars.USER_POOL_CLIENT_ID }}
