name: Deploy to AWS (prod)

on: workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        name: Deploy to AWS
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v7
              with:
                  node-version: 26

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint

            - name: Run tests
              run: npm run test

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.2.3
              with:
                  role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
                  aws-region: eu-west-2

            - name: Deploy
              run: npm run deploy
              env:
                  CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
                  DEPLOY_ENV: prod
